#!/usr/bin/env python3
"""
export_face_sprites.py
Converts face portrait sprite sheets to GotchiFaceSprites.h (C++ PROGMEM arrays).

Sheet format: horizontal strip, 12 frames x 120x67 px (= 1440x67 total)
Frame order:  NEUTRAL F0, NEUTRAL F1, HAPPY F0, HAPPY F1, SAD F0, SAD F1,
              SLEEPING F0, SLEEPING F1, EXCITED F0, EXCITED F1, STARTLED F0, STARTLED F1
"""
from PIL import Image
import os, textwrap

SCRIPT_DIR  = os.path.dirname(os.path.abspath(__file__))
SPRITES_DIR = os.path.join(SCRIPT_DIR, '..', 'sprites', 'gotchi')
OUTPUT_H    = os.path.join(SCRIPT_DIR, '..', '..', 'src', 'apps', 'gotchi', 'GotchiFaceSprites.h')

CREATURES   = ['bytee', 'cthulhu', 'jack', 'lumi']   # order matches CreatureType enum (0-3)
FRAME_W     = 120
FRAME_H     = 67
FRAMES      = 12    # 6 moods × 2 anim frames

def rgb_to_rgb565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)

def frame_origin(f, W, H):
    """Return (x0, y0) for frame index f given sheet dimensions W×H.
    Supports:
      - single-row strip:  W = FRAME_W*12,  H = FRAME_H   (lumi)
      - double-row strip:  W = FRAME_W*6,   H = FRAME_H*2 (jack/bytee/cthulhu)
    """
    cols = W // FRAME_W   # frames per row
    row = f // cols
    col = f % cols
    return col * FRAME_W, row * FRAME_H

def process_creature(name):
    path = os.path.join(SPRITES_DIR, f'{name}_sheet.png')
    img  = Image.open(path).convert('RGB')
    W, H = img.size
    total_frames = (W // FRAME_W) * (H // FRAME_H)
    assert total_frames == FRAMES, f"{name}: found {total_frames} frames, expected {FRAMES}  (sheet {W}x{H})"

    pixels = img.load()

    # Count color frequency across all frames
    freq = {}
    for f in range(FRAMES):
        x0, y0 = frame_origin(f, W, H)
        for py in range(FRAME_H):
            for px in range(FRAME_W):
                c = pixels[x0 + px, y0 + py]
                freq[c] = freq.get(c, 0) + 1

    # Sort by descending frequency (index 0 = most common = background)
    sorted_colors = sorted(freq, key=lambda c: -freq[c])
    n = len(sorted_colors)
    print(f"  {name}: {n} unique colors")
    assert n <= 256, f"{name}: too many colors ({n})"

    use_nibbles = n <= 16
    c2i = {c: i for i, c in enumerate(sorted_colors)}

    # RGB565 palette
    pal565 = [rgb_to_rgb565(r, g, b) for r, g, b in sorted_colors]

    # RLE-encode each frame: stream of (count, index) byte pairs
    # count = 1..255; a run of >255 identical pixels is split into multiple pairs
    encoded_frames = []
    for f in range(FRAMES):
        x0, y0 = frame_origin(f, W, H)
        indices = []
        for py in range(FRAME_H):
            for px in range(FRAME_W):
                indices.append(c2i[pixels[x0 + px, y0 + py]])

        rle = bytearray()
        i = 0
        while i < len(indices):
            val = indices[i]
            run = 1
            while i + run < len(indices) and indices[i + run] == val and run < 255:
                run += 1
            rle.append(run)
            rle.append(val)
            i += run
        encoded_frames.append(bytes(rle))

    return pal565, encoded_frames, n

def bytes_as_c_array(data, cols=16):
    """Format bytes as C hex literals, 'cols' per line."""
    lines = []
    for i in range(0, len(data), cols):
        chunk = data[i:i+cols]
        lines.append(', '.join(f'0x{b:02X}' for b in chunk))
    return ',\n    '.join(lines)

def u16_as_c_array(arr, cols=8):
    lines = []
    for i in range(0, len(arr), cols):
        chunk = arr[i:i+cols]
        lines.append(', '.join(f'0x{v:04X}' for v in chunk))
    return ',\n    '.join(lines)

MOOD_NAMES = ['NEUTRAL', 'HAPPY', 'SAD', 'SLEEPING', 'EXCITED', 'STARTLED']
CREATURE_ENUM = {'jack': 'JACK', 'bytee': 'BYTEE', 'cthulhu': 'CTHULHU', 'lumi': 'LUMI'}

def main():
    print("Processing creatures...")
    results = {}
    for name in CREATURES:
        pal, frames, n_colors = process_creature(name)
        results[name] = (pal, frames, n_colors)
        raw_bytes  = FRAME_W * FRAME_H
        rle_sizes  = [len(f) for f in frames]
        avg_rle    = sum(rle_sizes) // len(rle_sizes)
        ratio      = raw_bytes / avg_rle
        print(f"    {n_colors} colors, RLE avg {avg_rle}B/frame ({ratio:.1f}x), total {sum(rle_sizes)}B")

    lines = []
    lines.append("// AUTO-GENERATED by art/scripts/export_face_sprites.py -- do not edit manually")
    lines.append("// RLE format: stream of (count, palette_index) byte pairs, row-major order")
    lines.append("#pragma once")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append(f"static constexpr uint8_t FACE_W = {FRAME_W};")
    lines.append(f"static constexpr uint8_t FACE_H = {FRAME_H};")
    lines.append(f"static constexpr uint8_t FACE_FRAMES_PER_MOOD = 2;")
    lines.append(f"static constexpr uint8_t FACE_MOOD_COUNT = 6;")
    lines.append("")
    lines.append("// Maps Mood enum value (0-12) to face mood index (0-5: NEUTRAL HAPPY SAD SLEEPING EXCITED STARTLED)")
    lines.append("static constexpr uint8_t FACE_MOOD_MAP[13] = {")
    lines.append("    0, 1, 2, 0, 2, 3, 4, 1, 4, 0, 5, 5, 5")
    lines.append("};")
    lines.append("")

    for name in CREATURES:
        pal, frames, n_colors = results[name]
        UP = name.upper()
        total = sum(len(f) for f in frames)
        lines.append(f"// {UP}: {n_colors} palette colors, {total}B RLE total")
        lines.append(f"static constexpr uint8_t FACE_{UP}_COLORS = {n_colors};")
        lines.append(f"static constexpr uint16_t FACE_{UP}_PAL[{len(pal)}] = {{")
        lines.append(f"    {u16_as_c_array(pal)}")
        lines.append("};")
        lines.append("")
        for fi, frame_data in enumerate(frames):
            mood_idx  = fi // 2
            anim_idx  = fi % 2
            mood_name = MOOD_NAMES[mood_idx]
            lines.append(f"static constexpr uint8_t FACE_{UP}_{mood_name}_F{anim_idx}[{len(frame_data)}] = {{")
            lines.append(f"    {bytes_as_c_array(frame_data)}")
            lines.append("};")
        lines.append("")
        lines.append(f"static constexpr const uint8_t* FACE_{UP}_FRAMES[{FRAMES}] = {{")
        ptrs = []
        for fi in range(FRAMES):
            m, a = fi // 2, fi % 2
            ptrs.append(f"FACE_{UP}_{MOOD_NAMES[m]}_F{a}")
        lines.append(f"    {', '.join(ptrs)}")
        lines.append("};")
        lines.append("")

    lines.append("inline const uint8_t* getFaceFrameData(uint8_t ci, uint8_t faceMood, uint8_t animFrame) {")
    lines.append("    static constexpr const uint8_t* const* T[4] = {")
    for name in CREATURES:
        lines.append(f"        FACE_{name.upper()}_FRAMES,")
    lines.append("    };")
    lines.append("    return T[ci][(faceMood % 6) * 2 + (animFrame & 1)];")
    lines.append("}")
    lines.append("")
    lines.append("inline const uint16_t* getFacePalette(uint8_t ci) {")
    lines.append("    static constexpr const uint16_t* P[4] = {")
    for name in CREATURES:
        lines.append(f"        FACE_{name.upper()}_PAL,")
    lines.append("    };")
    lines.append("    return P[ci];")
    lines.append("}")

    output = '\n'.join(lines) + '\n'
    with open(OUTPUT_H, 'w', encoding='utf-8') as f:
        f.write(output)

    total_bytes = sum(sum(len(f) for f in frames) for _, frames, _ in results.values())
    print(f"\nGenerated: {OUTPUT_H}")
    print(f"Total PROGMEM: {total_bytes} bytes ({total_bytes/1024:.1f} KB)")

if __name__ == '__main__':
    main()
