#!/usr/bin/env python3
"""
spr2c.py — Aseprite sprite sheet PNG+JSON -> C header for Stick-Gotchi

Usage (from project root):
    python tools/spr2c.py art/sprites/gotchi/egg.json
    python tools/spr2c.py art/sprites/gotchi/blob_baby.json

Output:
    src/generated/sprites_<name>.h

Palette mapping (gotchi_sprite.gpl):
    index 0  #FF00FF  transparent
    index 1  #0000FF  primary    (replaced at runtime by GotchiDNA)
    index 2  #00FFFF  secondary
    index 3  #404040  dark
    index 4  #FFFF00  accent

Emote palette (emote.gpl):
    index 0  #FF00FF  transparent
    index 1  #FFFFFF  white
    index 2  #000000  black
    index 3  #FF4040  red
"""

import sys
import json
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    print("ERROR: Pillow not found. Run:  pip install Pillow")
    sys.exit(1)

# ---------------------------------------------------------------------------
# Palette definitions — RGB -> our 0-4 index
# ---------------------------------------------------------------------------

GOTCHI_PALETTE = {
    (255,   0, 255): 0,  # transparent
    (  0,   0, 255): 1,  # primary
    (  0, 255, 255): 2,  # secondary
    ( 64,  64,  64): 3,  # dark
    (255, 255,   0): 4,  # accent
}

EMOTE_PALETTE = {
    (255,   0, 255): 0,  # transparent
    (255, 255, 255): 1,  # white
    (  0,   0,   0): 2,  # black
    (255,  64,  64): 3,  # red
}

def _closest(rgb, palette_map):
    """Map an RGB tuple to the nearest palette index (Manhattan distance)."""
    best_idx, best_dist = 0, float('inf')
    for color, idx in palette_map.items():
        d = sum(abs(a - b) for a, b in zip(rgb, color))
        if d < best_dist:
            best_dist, best_idx = d, idx
    return best_idx

# ---------------------------------------------------------------------------
# PNG loading
# ---------------------------------------------------------------------------

def _load_sheet(png_path):
    """Return (width, height, flat_pixel_list_as_RGB_tuples)."""
    img = Image.open(png_path).convert('RGBA')
    w, h = img.size
    pixels = list(img.tobytes())
    rgba_pixels = [
        (pixels[i], pixels[i+1], pixels[i+2], pixels[i+3])
        for i in range(0, len(pixels), 4)
    ]
    return w, h, rgba_pixels

def _pixel_to_index(rgba, palette_map):
    r, g, b, a = rgba
    if a == 0:
        return 0  # fully transparent
    return _closest((r, g, b), palette_map)

# ---------------------------------------------------------------------------
# Frame extraction
# ---------------------------------------------------------------------------

def _extract_frame(pixels, sheet_w, fx, fy, fw, fh, palette_map):
    result = []
    for row in range(fh):
        for col in range(fw):
            px = pixels[(fy + row) * sheet_w + (fx + col)]
            result.append(_pixel_to_index(px, palette_map))
    return result

# ---------------------------------------------------------------------------
# C code generation
# ---------------------------------------------------------------------------

def _arr_name(sprite_name, tag_name, frame_idx):
    return f"SPR_{sprite_name.upper()}_{tag_name.upper()}_F{frame_idx}"

def _format_rows(data, w, h):
    lines = []
    for row in range(h):
        chunk = data[row * w:(row + 1) * w]
        lines.append("    " + ",".join(str(v) for v in chunk) + ",")
    return lines

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def generate(json_path_str, output_dir_str=None, emote_mode=False):
    json_path = Path(json_path_str).resolve()
    sprite_name = json_path.stem  # e.g. "egg", "blob_baby"

    # PNG is next to JSON (Aseprite default export)
    png_path = json_path.with_suffix('.png')
    if not png_path.exists():
        # also try the "image" field in JSON
        with open(json_path) as f:
            d = json.load(f)
        img_name = d.get('meta', {}).get('image', '')
        png_path = json_path.parent / img_name
    if not png_path.exists():
        print(f"ERROR: PNG not found: {png_path}")
        sys.exit(1)

    with open(json_path) as f:
        data = json.load(f)

    palette_map = EMOTE_PALETTE if emote_mode else GOTCHI_PALETTE

    sheet_w, sheet_h, pixels = _load_sheet(png_path)
    frames_dict = data['frames']
    frame_keys  = list(frames_dict.keys())
    tags        = data['meta']['frameTags']

    # Output path
    if output_dir_str:
        out_dir = Path(output_dir_str)
    else:
        # assume script is run from project root → src/generated/
        out_dir = Path('src/generated')
    out_dir.mkdir(parents=True, exist_ok=True)
    out_file = out_dir / f"sprites_{sprite_name}.h"

    # Build file content
    lines = [
        f"// AUTO-GENERATED by tools/spr2c.py — do not edit",
        f"// Source: {json_path.name}",
        f"#pragma once",
        f"#include <stdint.h>",
        f"",
        f"// Palette indices: 0=transparent 1=primary 2=secondary 3=dark 4=accent",
        f"",
    ]

    first_frame = frames_dict[frame_keys[0]]['frame']
    sprite_w, sprite_h = first_frame['w'], first_frame['h']

    for tag in tags:
        tag_name   = tag['name']
        from_frame = tag['from']
        to_frame   = tag['to']

        lines.append(f"// ── {sprite_name} / {tag_name} {'─' * max(0, 50 - len(sprite_name) - len(tag_name))}")

        for local_idx, global_idx in enumerate(range(from_frame, to_frame + 1)):
            finfo = frames_dict[frame_keys[global_idx]]['frame']
            frame_data = _extract_frame(
                pixels, sheet_w,
                finfo['x'], finfo['y'], finfo['w'], finfo['h'],
                palette_map
            )
            arr = _arr_name(sprite_name, tag_name, local_idx)
            lines.append(f"constexpr uint8_t {arr}[{finfo['h']}*{finfo['w']}] = {{")
            lines.extend(_format_rows(frame_data, finfo['w'], finfo['h']))
            lines.append(f"}};")
            lines.append(f"")

    # Constants
    lines.append(f"// Sprite size")
    lines.append(f"constexpr uint8_t {sprite_name.upper()}_W = {sprite_w};")
    lines.append(f"constexpr uint8_t {sprite_name.upper()}_H = {sprite_h};")
    lines.append(f"")
    lines.append(f"// Frame counts per tag")
    for tag in tags:
        count = tag['to'] - tag['from'] + 1
        lines.append(f"constexpr uint8_t {sprite_name.upper()}_{tag['name'].upper()}_FRAMES = {count};")

    out_file.write_text("\n".join(lines) + "\n", encoding='utf-8')
    print(f"OK  {out_file}  ({sprite_w}x{sprite_h}px, {len(tags)} tags, {len(frame_keys)} frames)")

if __name__ == '__main__':
    args = sys.argv[1:]
    if not args:
        print(__doc__)
        sys.exit(1)

    emote = '--emote' in args
    args  = [a for a in args if not a.startswith('--')]

    json_path  = args[0]
    output_dir = args[1] if len(args) > 1 else None
    generate(json_path, output_dir, emote_mode=emote)
